apiVersion: v1
kind: Pod
metadata:
  name: mypod5
  labels:
    app: mylabel
spec:
  containers:
    - name: mypython
      image: python:3.6
      command: ["slee"]
      args: ["99999"]
      resources:
        requests:
          memory: "64Mi"
          cpu: "500m"
        limits:
          memory: "128Mi"
          cpu: "1"
